### ISSUE TITLE
使用ijkplayer播放视频时，音视频不同步

### ISSUE THREAD

**Issue by LiuHanzhi** [jiajunhui/PlayerBase#103]
[record.zip](https://github.com/jiajunhui/PlayerBase/files/3770292/record.zip)

在很多设备上，使用ijplayer解码播放某些视频(MP3或者m3u8格式)时，会出现音视频不同步的问题，切换至MediaPlayer解码或者ExoPlayer解码时不会出现此问题，不确定是否是因为视频分辨率教高导致，我播放的是1080p的视频，使用哔哩哔哩开源框架里的ijkplayer demo播放此视频，也不会出现音视频不同步的问题。
查看代码里关于此块代码上的差异，感觉像是RenderTextureView与播放器绑定上的问题导致，但是仔细对比了两者代码，依然没发现问题出在哪里。

代码版本：ijkplayer demo，tag k0.8.8；PlayerBase master分支最新代码。
设备：创维小度AI电视盒子（Q3011），Android系统版本 7.0

**Comment by jiajunhui** [comment]
可自己定制解码配置试试
