### ISSUE TITLE
无缝续播问题

### ISSUE THREAD

**Issue by zzh12138** [jiajunhui/PlayerBase#12]
续播是不是对解码器有要求的，发现如果注释掉demo中App的ijk和exo player，使用默认的mediaplayer，续播会出现问题

**Comment by jiajunhui** [comment]
使用MediaPlayer时，之前发现了一点小问题，就是重新关联Surface后有时视频会跳动几秒，有时是正常的，这个问题有待讨论是否属于解码器特性还是bug。不知道你指的是不是这个问题。
如有问题，请尽量进交流群（600201778）讨论。
