### ISSUE TITLE
关于mStartPos的机制问题

### ISSUE THREAD

**Issue by NerdAnonymous** [jiajunhui/PlayerBase#129]
在ExoMediaPlayer类中的start(int msc)方法中给mStartPos赋值会出现无效问题。出现场景是当我设置了datasource后，不调用start的方法，然后用一个按钮去点击再去调用start的方法，这样在onPlayerStateChanged中的mInternalPlayer.seekTo(mStartPos)不会在触发了，因为已经isPreparing过了，不会走到这个条件里面，导致mStartPos赋值后无法被seekTo。总结来说，就是我只要不同时调用setDataSource()和start()方法，就会造成mStartPos失效。

**Comment by jiajunhui** [comment]
已修复，使用最新版本
