### ISSUE TITLE
关于前后台切换暂停问题

### ISSUE THREAD

**Issue by NerdAnonymous** [jiajunhui/PlayerBase#130]
前后台切换的时候，按照demo的BaseVideoViewActivity中的逻辑，进入后台暂停成功，进入前台调用resume方法。正常流程没什么问题，但是当你在进入后台之前去拖动进度条，进度条的下一个画面还没来得及渲染，你就进入后台了，然后再次进入前台时，首先它会优先走onRenderedFirstFrame这个逻辑，然后更新了状态变成STATE_STARTED，然后再走resume的方法，这时候状态由本来的STATE_PAUSED变成STATE_STARTED造成无法进行resume操作，个人觉得是不是可以去掉onRenderedFirstFrame中的updateStatus

**Comment by jiajunhui** [comment]
没太理解你的意思

**Comment by NerdAnonymous** [comment]
@jiajunhui 简单的说 就是我进入后台是pause状态，然后再进入前台的时候应该是onresume状态，但是在onresume状态之前执行了onRenderedFirstFrame的方法，把状态更新成STATE_STARTED,造成resume方法中的STATE_PAUSED不成立，导致resume无法执行

**Comment by jiajunhui** [comment]
你指的是ijk的包装中的resume和pause实现有问题是吗？

**Comment by NerdAnonymous** [comment]
> 你指的是ijk的包装中的resume和pause实现有问题是吗？

不是 该怎么跟你描述这个问题 我弄个流程
