### ISSUE TITLE
RelationAssist在recyclerview中使用

### ISSUE THREAD

**Issue by admasterlu** [jiajunhui/PlayerBase#131]
您好，RelationAssist在recyclerview中使用，RelationAssist的依赖view上面有个TextView点赞数量。切换到某一个item，视频正常播放，此时调用adapter的notifyItemChanged(pos)刷新item的点赞数量，关联助手会停止工作，我该怎么让视频正常播放不中断呢

**Comment by jiajunhui** [comment]
可采用对TextView设置tag的方式，使用RecyclerView的findViewWIthTag()找到对应的View去做更新操作。

**Comment by admasterlu** [comment]
感谢提供思路

**Comment by admasterlu** [comment]
刚才看到您发布一个新版本，试了一下，和之前相比，视频正常播放，音频会延迟几秒..是bug还是新版需要设置什么？

**Comment by jiajunhui** [comment]
暂未发现你说的情况，新版本升级了exo的核心库版本。
