### ISSUE TITLE
是否可以提供自定义TimerCounterProxy的能力，或者可以自定义间隔，现在时长1S，在视频比较短的时候，进度条不够平滑

### ISSUE THREAD

**Issue by fanwc** [jiajunhui/PlayerBase#135]

**Comment by fanwc** [comment]
我现在是这样做的，希望可以尽快提供官方api
`public void setProgressIntervalTime(int intervalTime) {
        try {
            Field player =  mRelationAssist.getClass().getDeclaredField("mPlayer");
            player.setAccessible(true);
            AVPlayer playerValue = (AVPlayer) player.get(mRelationAssist);
            Field timeProxy = playerValue.getClass().getDeclaredField("mTimerCounterProxy");
            timeProxy.setAccessible(true);
            TimerCounterProxy proxyValue = (TimerCounterProxy) timeProxy.get(playerValue);
            Field counterInterval = proxyValue.getClass().getDeclaredField("counterInterval");
            counterInterval.setAccessible(true);
            counterInterval.set(proxyValue,intervalTime);
            long end = System.currentTimeMillis();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`

**Comment by jiajunhui** [comment]
已增加，见最新版本
