### ISSUE TITLE
非常好的库，有考虑过exoPlayer增加对RTMP直播流的支持吗？

### ISSUE THREAD

**Issue by xiaobaDev** [jiajunhui/PlayerBase#137]
感谢作者，项目中已经使用该库。

另外有直播需求，exoPlayer原始支持hls直播流，用官方扩展库可以增加对rtmp的支持。作者有考虑扩展exoPlayer吗？
https://blog.csdn.net/u010302327/article/details/103718182

**Comment by jiajunhui** [comment]
可以的，只是我目前没时间，后面我找时间加一下。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;kimmy&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月29日(星期二) 下午4:19
收件人:&nbsp;&quot;jiajunhui/PlayerBase&quot;<PlayerBase@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jiajunhui/PlayerBase] 非常好的库，有考虑过exoPlayer增加对RTMP直播流的支持吗？ (#137)

**Comment by jiajunhui** [comment]
经测试对于rtmp的拓展，直接引入拓展库即可，无需代码上的变更。
implementation  'com.google.android.exoplayer:extension-rtmp:2.X.X' 
详见 https://github.com/google/ExoPlayer/blob/release-v2/extensions/rtmp/README.md
