### ISSUE TITLE
playerbase 播放直播视频！

### ISSUE THREAD

**Issue by weizheng15828676432** [jiajunhui/PlayerBase#15]
您写的这个好像不能播放直播视频 ，或许我没有找到设置 ！如果您有空能方便通知我一下吗？谢谢！

**Comment by jiajunhui** [comment]
demo中使用的解码器是点播用的，如果要处理直播，编译一份支持直播的解码库接入即可。

**Comment by hopelesszxq** [comment]
编译支持直播的解码库接入，还是实现不了直播，测试视频有时间显示，现象就是初步加载，播放时视频是快进形式，播到当前时间就会停止，进入缓存状态，大约10-30秒继续播放，还是快进形式，播到最新时间就会重复前面的过程，请问这是怎么回事

**Comment by jiajunhui** [comment]
看你的描述，播放到当前时间应该是进入缓冲状态了。受网络状态和视频源影响，按说缓冲是正常的现象。不太清楚你要表达的问题。
