### ISSUE TITLE
怎么设置循环播放

### ISSUE THREAD

**Issue by handsomezwj** [jiajunhui/PlayerBase#16]

**Comment by jiajunhui** [comment]
可以在自己接入的解码器中自行实现，也可在播放完成的回调中调用rePlay(0)实现。目前框架定义的API暂无Loop设置项。

**Comment by netdolphin** [comment]
我也遇到这个问题，用了rePlay(0)无效。控制台反复出现
04-08 12:34:27.252 28477-28477/BaseActivity: onPlayerEvent: **********PAUSE
04-08 12:34:27.319 28477-28477/BaseActivity: onPlayerEvent:********** RESUME
04-08 12:34:27.381 28477-28477/BaseActivity: onPlayerEvent: **********PAUSE
04-08 12:34:27.319 28477-28477/BaseActivity: onPlayerEvent:********** RESUME

**Comment by netdolphin** [comment]
在调用replay之前加入
getReceiverGroup().getGroupValue().putBoolean(DataInter.Key.KEY_COMPLETE_SHOW, false);
也无效

**Comment by jiajunhui** [comment]
replay之前设置过数据了吗？

**Comment by netdolphin** [comment]
没有

**Comment by netdolphin** [comment]
是在onPlayerEvent的监听回调中直接调用replay(0)的

**Comment by jiajunhui** [comment]
进群详聊，发下你的操作代码。

**Comment by netdolphin** [comment]
我怀疑一个有Ireceriver在一直发送播放停止的event事件，所以反复出现pause和resume。加了getReceiverGroup().getGroupValue().putBoolean(DataInter.Key.KEY_COMPLETE_SHOW, false);也一样

**Comment by netdolphin** [comment]
群里没人响应啊
