### ISSUE TITLE
播放flv格式文件，插上耳机有声音，不插耳机，声音低的听不清

### ISSUE THREAD

**Issue by chengdh** [jiajunhui/PlayerBase#19]
播放flv格式文件，插上耳机有声音，不插耳机，声音低的听不清http://vodtv1mhgc2.vod.126.net/vodtv1mhgc2/LUiQhEif_1722088671_sd.flv

**Comment by jiajunhui** [comment]
你这个资源转码有问题，试了多个播放器，声音都是滋滋的尖锐声。

**Comment by chengdh** [comment]
但是在小米手机上正常有声音啊

**Comment by jiajunhui** [comment]
把ijk切到软解码试试

**Comment by jiajunhui** [comment]
十有八九就是转码问题，我试了小米4播放也有问题，我用电脑播放器播放同样有问题。找到原始资源重新转码试试吧。
