### ISSUE TITLE
用系统的MediaPlayer播放器，暂停切换屏幕会出现绿屏

### ISSUE THREAD

**Issue by ethanhua** [jiajunhui/PlayerBase#20]
库很不错，感谢作者的开源，如题 我使用库后会出现绿屏的问题，手机为Meizu mi metal android5.1 api22
出现场景为： 暂停播放后切换屏幕会出现绿屏（全屏操作或者跳到第二个页面再回来）, 该库例子中使用的是 ijkplayer 改为系统播放器后，也会重现这个绿屏的问题

**Comment by jiajunhui** [comment]
绿屏一般都是硬解码的问题，把ijk设置软解码试试。
