### ISSUE TITLE
循环播放本地视频，播放前总会loading一下

### ISSUE THREAD

**Issue by GuoSirNB** [jiajunhui/PlayerBase#22]
网络视频缓存到本地，再播放本地视频，为什么会loading一下，播放结束重播时也是，请问怎么把这个逻辑去掉

**Comment by jiajunhui** [comment]
本地的视频，解码器同样需要prepare的时间，只不过本地会很快，Loading可能一闪而过，但不代表不需要。如果你想去掉，请在LoadingCover中播放本地资源时自行标示处理。
