### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by SnowsonZ** [jiajunhui/PlayerBase#23]
demo导入AS后，没有成功依赖support v7及ijkplayer,exoplayer lib。而且项目并没有依赖support-v4包。
是我本地环境的原因吗？
![image](https://user-images.githubusercontent.com/12555482/42315497-2e24422c-807a-11e8-90bd-c083c9c1ede3.png)
![image](https://user-images.githubusercontent.com/12555482/42315528-4518d402-807a-11e8-9e30-233f58ffffb1.png)
![image](https://user-images.githubusercontent.com/12555482/42315572-5f9233fa-807a-11e8-917d-7f169f9cf9fa.png)

**Comment by SnowsonZ** [comment]
对了，虽然存在上述问题，但是可以成功跑起来，不太清楚这是什么原因

**Comment by jiajunhui** [comment]
@SnowsonZ 不是代码问题，我也遇到过，clean或者重启大法。有问题加群讨论吧。
