### ISSUE TITLE
同一CoverLevel中的Cover怎么区分显示层级？

### ISSUE THREAD

**Issue by Elivish** [jiajunhui/PlayerBase#24]
现在是对不同的CoverLevel设计3个不同的组别层级，但是在实际中，可能UI组件需要多于三个的显示层级顺序。但在同一Level层级中，要区分它们的显示顺序是做不到的(代码中是在ReceiverGroup中使用Set的增强for循环遍历Cover，这个在不同的JDK版本得出的结果可能不一样，可能根据key的hashCode得到一种有序的结果)。所以建议设计CoverLevel为int值(类似ZOrder的概念)，来区分不同的显示层级。
还有既然设计了IReceiverGroup接口，为什么在xxx.setReceiverGroup(ReceiverGroup r)方法中，不指定参数为IReceiverGroup而是直接使用ReceiverGroup实现类？我想改你的forEach方法都做不到。。

**Comment by jiajunhui** [comment]
这个问题我之前想到过了，大部分场景下使用三个CoverLevel是能满足的。如果目前不能满足的话，你还可以重写SuperContainer然后传入自定义的ICoverStrategy来实现层级的填充规则。目前我在独立分支下正在优化层级的合理填充这块，后期会更新。

**Comment by jiajunhui** [comment]
@Elivish 3.3.0版本已发布，有需要可以看一下，有问题再反馈。
