### ISSUE TITLE
 update and improvement of the logo PlayerBase

### ISSUE THREAD

**Issue by orlant** [jiajunhui/PlayerBase#25]
hello for me it's a pleasure to greet you, my name is Orlando, I'm a graphic designer and I like to collaborate on open source projects, if I may, I can design a new image for the use of this application? innovative and attractive to the eye

**Comment by jiajunhui** [comment]
Thanks for your attention and suggestions. Is your design free or not?

**Comment by orlant** [comment]
you're welcome. my collaboration is totally free friend, would be a satisfaction for me, reach the final goal, which is to see it added in your repository, if you have met all the requirements, happy to design for you

**Comment by jiajunhui** [comment]
OK, Thanks. I'm glad to get your help. Before you design, do you need me to provide some information about the repository?

**Comment by orlant** [comment]
ok, to feed me more, I had read the information of this project before and I have already started making some drafts, which is the first stage at this moment I am digitizing the idea that will be presented shortly. thank you very much

**Comment by jiajunhui** [comment]
PlayerBase is an Android player base library, which is a highly decoupled solution for decoder and view components. This is equivalent to component-based processing of the decoder and view. The access is simple and easy to use. The above is a general description of the whole frame, and I hope it will be helpful for your design. Thank you again for your design.

**Comment by orlant** [comment]
hello good night this has been my logo contribution. the logo happened to the play button of a player that was combined at the same time with the letter A that chose it from the previous logo. I used a color palette associated with the colors that you already have used in your current logo.

![presentacion1](https://user-images.githubusercontent.com/40074778/42427930-2c966fc0-82ff-11e8-8f8a-1c2482668134.png)

Three types of different fonts and color variation:
![presentacion2](https://user-images.githubusercontent.com/40074778/42427976-532503ea-82ff-11e8-9e5f-b792712a0f36.png)

It also has a LogoMark icon but if you want I can use it if the protection zone
![icons](https://user-images.githubusercontent.com/40074778/42428018-81ae3024-82ff-11e8-8c70-11bbe5476daa.png)

**Comment by orlant** [comment]
feel free to make corrections and improvements the important thing is that you feel satisfied with the logo ...

**Comment by jiajunhui** [comment]
The design style is very good. I like third types of fonts and second icons.

**Comment by orlant** [comment]
HAVE YOU STILL HERE ?, I will do the combination of the type of source you like most and the icon that you chose to see the final result

**Comment by jiajunhui** [comment]
Yes, I'm here, and I'm looking forward to the final result.

**Comment by orlant** [comment]
look I have combined the logo you chose with the font style CodeBolt that is very elegant in my opinion ... and look what came out now you have to Choose from these 2 models ... What will be the winner ???

![listooo](https://user-images.githubusercontent.com/40074778/42437082-edec5e30-8329-11e8-989a-eb0f21d78c5b.png)

**Comment by jiajunhui** [comment]
I prefer the plan B, Do you have any good suggestions?

**Comment by orlant** [comment]
I feel satisfied and at ease of this work that I have done for you from the beginning this was the favorite result and seeing that you going through a couple of filters, you have chosen it I am happy ... I would like to see it renewed in your repository...
  But now tell me if you are happy, as much as I am? to load all the files you need ready to use in all formats, if you have any specific measure that you need the logo you can let me know.

**Comment by jiajunhui** [comment]
Excuse me, can you turn the letter into a lowercase? I want to see the effect of the lower case. thanks.

**Comment by jiajunhui** [comment]
PLAYERBASE --> PlayerBase

**Comment by orlant** [comment]
WITH MUCH TASTE, but I will have to change the style of text to a similar one, since this type of font only comes with uppercase letter you want, to show you with other sources?

**Comment by orlant** [comment]
1
![arial](https://user-images.githubusercontent.com/40074778/42438710-d14292b8-832e-11e8-8d64-e0b508309964.png)
2
![gautami](https://user-images.githubusercontent.com/40074778/42438723-dadaacde-832e-11e8-842f-98393b4ffe82.png)

here are for visualizes but with two types of sources more similar possible than if they come in the download package with letters mini-letters

**Comment by jiajunhui** [comment]
I think the lowercase is a little better. However, these two pictures seem to be the same. 
![image](https://user-images.githubusercontent.com/8542947/42439341-39fecc5c-8395-11e8-8637-fb32323f896d.png)
I like this icon. I want to use it as my APP icon. 
If possible. I hope it's in the PNG format. Thank you very much.

**Comment by orlant** [comment]
then tell me what the final result will be ??? East??

![gautami](https://user-images.githubusercontent.com/40074778/42439744-b2997acc-8331-11e8-9bc3-7a8a669a9aba.png)
 


with respect to the icon, if I have them in PNG, SVG, AI, PDF, PSD, EPS ready to use and not just that icon, but I will send you a pack with different colors, if in the future you need to use it in networks, or innovate the colors are already stored. So now if you can close this case? to send you all the files?

**Comment by orlant** [comment]
if you are so kind please can you tell me if you will keep that logo and if we have finished you can close the ISSUES. To proceed to send you all the corresponding files

**Comment by orlant** [comment]
Excuse me for making you wait. If you need something else, you can tell me ...

Here are all the files ready to use.!

https://drive.google.com/open?id=1WpbINNF4Rg-f9aus2BCazCH4-urnrNpu

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.

**Comment by orlant** [comment]
Excuse me here are the files updated in lowercase letter as I had said. I had wrong here are all the logo files already updated

[UPDATED FILES](https://drive.google.com/open?id=1WpbINNF4Rg-f9aus2BCazCH4-urnrNpu)

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.

**Comment by jiajunhui** [comment]
I've already downloaded it. Thank you very much.
