### ISSUE TITLE
GroupValue的一点改进建议

### ISSUE THREAD

**Issue by Elivish** [jiajunhui/PlayerBase#28]
GroupValue现在是receiver group的数据共享池，在每次调用putXXX系列方法时，除了把value存起来都会去遍历内部 OnGroupValueUpdateListener，这样做基本没错。但是有时候有些需求单纯的只是想存值，然后在某些时候拿出来用，而不想去遍历各种listener。
比如说，在controller中调节进度条onProgressChanged的时候，我想存值。但是每次存值都会去遍历listener并回调一些方法，固然可以通过filterKeys去过滤这些lietener。但是由于这个onProgressChanged回调的次数很多，所以GroupValue去遍历回调各种listener的次数也很多，这样就会造成一定的效率问题。
这个例子是在说，在你需要频繁的去改变数据共享池的时候，一些需求只是单纯的存储数据，但是附带的遍历回调会带来效率问题。
所以希望提供这样的接口，给putXXX系列方法一个flag，表示是否去遍历回调listener，
比如 putInt(int key, int value, boolean isNotifyCallback)

**Comment by jiajunhui** [comment]
感谢你的提醒，看来你看的还挺细致。整个框架近万行代码，难免有些不足之处，这些问题我都会慢慢改进。之前是对遍历和查找做了优化。稍安勿躁，我会慢慢逐步排查问题。

**Comment by jiajunhui** [comment]
@Elivish 3.3.0.2小幅更新。添加了GroupValue的是否通知回调参数设置。
