### ISSUE TITLE
请问支持字幕吗？

### ISSUE THREAD

**Issue by tmxd09887** [jiajunhui/PlayerBase#29]
添加字幕

谢谢

**Comment by jiajunhui** [comment]
如果你接入的解码器支持就可以添加字幕。框架自带的解码实现，MediaPlayer可以添加字幕（api >= 16）。其他解码器需要自行确认是否能添加字幕。如果可以，其实自己也可以做字幕对接，就像解析显示歌词一样。

**Comment by tmxd09887** [comment]
DataSource dataSource = new DataSource();
这个datasource里并不能给例如exoplayer添加字幕啊？

**Comment by jiajunhui** [comment]
请尝试最新版本
