### ISSUE TITLE
Window播放可以不依赖Activity吗

### ISSUE THREAD

**Issue by kjsolo** [jiajunhui/PlayerBase#34]
比如我想Window播放，然后返回上一个界面操作其他事件

**Comment by jiajunhui** [comment]
可以的，demo中的示例在页面销毁时把window也销毁了。你改为不销毁就可以了，同时注意把window的context设置为application的。

**Comment by kjsolo** [comment]
你的意思是说是使用WindowVideoView，而不是使用FloatWindow对吗，其实我对这两个的区别还是不太明白，即使看了文档。

**Comment by jiajunhui** [comment]
@kjsolo WindowVideoView是继承自BaseVideoView的，其实就相当于一个VideoView，具备设置播放功能，只不过是以window形式展现的。而FloatWindow是一个单纯的View，只是一个window容器，不带播放功能，可以用于切播（比如Layout播放时切播到window，就使用FloatWindow）。如果不需要切播，单纯的就只有window播放，那就直接使用WindowVideoView。
这里面交流不便，加群交流吧。
