### ISSUE TITLE
全屏时，如何根据视频的宽高自动调整横向显示还是竖向显示

### ISSUE THREAD

**Issue by kjsolo** [jiajunhui/PlayerBase#35]
如题

**Comment by jiajunhui** [comment]
没太明白你的意思。全屏时，横向竖向一般是随屏幕旋转的，如果想自己调整画面显示角度，可以用Render设置旋转角度。

**Comment by kjsolo** [comment]
比如说，这个视频是手机拍摄出来，这么视频的方向就是竖向的，全屏播放的时候就能填满整个手机

**Comment by jiajunhui** [comment]
PLAYER_EVENT_ON_VIDEO_SIZE_CHANGE可以获取到视频宽高，根据视频宽高自行调整如何显示。
