### ISSUE TITLE
视频播放横竖屏切换黑屏问题

### ISSUE THREAD

**Issue by AnJiuZhe** [jiajunhui/PlayerBase#36]
大佬好，请教一个问题，视频切换到横屏播放时，然后暂停播放，再切回到竖屏，这个时候并没有横屏播放时暂停的那一帧画面，而是黑屏。同理，竖屏暂停切横屏也会出现这种情况，请问这个要怎么处理呢？

**Comment by AnJiuZhe** [comment]
你好，在你的demo中设置了渲染视图用TextureView还是会出现这种情况，不知道怎么解决


在AssistPlayer中：
private AssistPlayer(){
        mAppContext = App.get().getApplicationContext();
        mRelationAssist = new RelationAssist(mAppContext);
        **mRelationAssist.setRenderType(IRender.RENDER_TYPE_TEXTURE_VIEW);**
        mRelationAssist.setEventAssistHandler(mInternalEventAssistHandler);
        mRelationAssist.getSuperContainer().setBackgroundColor(Color.BLACK);
        mOnPlayerEventListeners = new ArrayList<>();
        mOnErrorEventListeners = new ArrayList<>();
        mOnReceiverEventListeners = new ArrayList<>();
}

**Comment by jiajunhui** [comment]
@AnJiuZhe 群里聊吧，这里不方便。

**Comment by AnJiuZhe** [comment]
好的，谢谢。
