### ISSUE TITLE
视频播放时loading层展示

### ISSUE THREAD

**Issue by xinghedazhan** [jiajunhui/PlayerBase#4]
进在线视频列表，随机点击一个视频，在缓冲的时候，条目里面的视频view 有 loading 层展示，这时候再点击条目的跳转展示大屏播放，在大屏里面缓冲完毕播放，点击关闭返回列表页，列表里面的视频在播放 但是 loading层没有去掉，依然展示

**Comment by jiajunhui** [comment]
感谢反馈，bug已修复，如有需要，更新查看即可。
