### ISSUE TITLE
内存泄漏的问题

### ISSUE THREAD

**Issue by guozhiqiang123** [jiajunhui/PlayerBase#40]
![2018-08-19_225209](https://user-images.githubusercontent.com/20378988/44310045-90247b80-a402-11e8-8ce9-9a2ec89d5479.png)
将外部承载播放界面的Activity泄漏了，这个该怎么解决啊？

**Comment by jiajunhui** [comment]
你就贴这么一张图，没法定位问题。群里说吧。
