### ISSUE TITLE
可否增加一个 AspectRatio_FILL_WIDTH

### ISSUE THREAD

**Issue by liubaoyua** [jiajunhui/PlayerBase#44]
布局方式是充满 renderView的测量宽度，高度根据比例计算。

比如 RenderMeasure.doMeasure 里的 四个变量：
```
widthSpecSize，
heightSpecSize，
mVideoWidth,
mVideoHeight,
```

使测量结果为：
```
mMeasureWidth = widthSpecSize
mMeasureHeight = widthSpecSize * mVideoHeight / mVideoWidth
```

**Comment by jiajunhui** [comment]
@liubaoyua 这么做保证了画面比例，但是可能会出现边缘画面超出边界而不可见的情况。

**Comment by jiajunhui** [comment]
@liubaoyua 正好我今天发新版，加上了你说的这种填充方式。不过一般情况下的需求不会使用这种填充模式，除非特殊需求。

**Comment by liubaoyua** [comment]
@jiajunhui 感谢作者，这个需求确实不太常见，因为它基本有代替的方案。

类似微博 知乎，在列表中 View 会限制成 16：9 的比例，视频只显示中间部分，效果与 AspectRatio_FILL_PARENT 一样。

然后详情页因为是竖屏全屏，效果就和 AspectRatio_FIT_PARENT 差不多。（视频比例小于屏幕比例就不一样，比如全面屏手机拍的视频放到 9: 16 的手机上播放，不过我更倾向于截掉顶部底部）

因为我想做一个 由列表到全屏的转场动画，由列表中的宽高逐渐变换成全屏的宽高，所以想到设定 AspectRatio_FILL_WIDTH 就可以确保在动画的过程中是逐渐展开的。
