### ISSUE TITLE
demo里无法播放在线的MPEG编码的MP4文件，但是ijkplayer不是已经支持播放MPEG了吗

### ISSUE THREAD

**Issue by iamluyou** [jiajunhui/PlayerBase#45]

**Comment by jiajunhui** [comment]
@woyiluyou 提供一下视频资源。

**Comment by woyiluyou** [comment]
http://void.51im.com/server-resource/files/5b98b4f22a730a0ac9dd1296

**Comment by woyiluyou** [comment]
@jiajunhui

**Comment by jiajunhui** [comment]
@woyiluyou 刚刚试了下，应该是ijk的处理上的问题，并不是不支持，如果不支持，一开始就会抛出不支持的异常了，但是日志并没有，只是报了一个IJKMEDIA: stream 0, offset 0x43: partial file这种Error日志，就走播放完成的回调了。我试过了exo是没问题的，可以播放。

**Comment by jiajunhui** [comment]
@woyiluyou 你检查下你的视频文件是不是有问题。MediaPlayer也播不了，抛出了一个java.net.ProtocolException异常。exo虽然能播，其实也输出了一个和其他播放器一样的红色日志Can not get hwsched service。可能是视频源的文件不规范，我猜测。

**Comment by jiajunhui** [comment]
@woyiluyou chrome浏览器播放只有声音，没有图像。

**Comment by woyiluyou** [comment]
http://void.51im.com/server-resource/files/5b98b4f22a730a0ac9dd1296?type=download 可以下载视频源文件，这个下载下来的文件是可以用ijk播放的

**Comment by woyiluyou** [comment]
mp4格式的有h.264和mpeg4,我这边服务器传上去的h.264的MP4都可以正常播放，但是h.264的就有问题

**Comment by woyiluyou** [comment]
mp4格式的有h.264和mpeg4,我这边服务器传上去的h.264的MP4都可以正常播放，但是mpeg的就有问题

**Comment by jiajunhui** [comment]
@woyiluyou 基本能确定是你们的服务器问题，我把文件放到我本地的服务器播放，完全没问题。

**Comment by woyiluyou** [comment]
多谢，我再检查下
