### ISSUE TITLE
视频缓冲完，没网状态下拖动进度条后，视频无法继续播放

### ISSUE THREAD

**Issue by DarianLiu** [jiajunhui/PlayerBase#46]
视频缓冲完，没网状态下拖动进度条后，视频无法继续播放，这个体验不是很好

**Comment by DarianLiu** [comment]
拖动进度条无法准确获取当前进度是否缓冲完成

**Comment by DarianLiu** [comment]
网络视频列表，设置自动播放，频繁进出覆盖层不显示

**Comment by 574759229** [comment]
我也遇到这个问题了

> 视频缓冲完，没网状态下预先进度条后，视频无法继续播放，这个体验不是很好

**Comment by ikakaxi** [comment]
我也遇到这个问题了
