### ISSUE TITLE
window播放

### ISSUE THREAD

**Issue by zzh12138** [jiajunhui/PlayerBase#5]
刚下了demo试了下，窗口播放应该是要权限的吧，没给权限直接点窗口播放就白屏了，是不是没做权限的判断？
手机是：魅蓝5s 6.0系统

**Comment by jiajunhui** [comment]
之前demo用的window类型为TYPE_TOAST，因有些手机禁止了该类型，所以demo刚修改为TYPE_SYSTEM_ALERT，有些手机需要手动开启悬浮窗权限才能正常使用。window权限是不能动态申请的。你重新下载下demo手动授予权限试试。
