### ISSUE TITLE
您好，遇到一个无法播放的视频，然后整个列表的视频都会显示这个，找不到原因了，您能帮我分析下吗

### ISSUE THREAD

**Issue by chengh2016** [jiajunhui/PlayerBase#52]
![tim 20181013094355](https://user-images.githubusercontent.com/18166794/46899947-11f9c800-cecd-11e8-8f93-9af350b64e4c.png)

**Comment by jiajunhui** [comment]
有日志吗？

**Comment by chengh2016** [comment]
使用的ijkPlayer,一遇到那个无法播放的视频，其他正常的视频再点击也都无法播放了，菜鸟级程序员求解

   W/IJKMEDIA: Failed to open segment of playlist 0
   E/IJKMEDIA: Error when loading first segment 'https://cm14-ccm1-2.play.bokecc.com/flvs/E6121B74B8F0AB41/2018-06-19/861403B8CF3170659C33DC5901307461-10.ts?video=0'
  E/IJKMEDIA: https://cm14-ccm1-2.play.bokecc.com/flvs/E6121B74B8F0AB41/2018-06-19/861403B8CF3170659C33DC5901307461-10.m3u8?t=1539442299&key=721B5DFB8D570EFFCA92F1CF91D81436&version=android_2.14.1: Invalid data found when processing input
   I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9013]
  D/IJKMEDIA: FFP_MSG_ERROR: 0
  E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
  I/trustAllHosts: checkServerTrusted
  I/http response code: 204

**Comment by jiajunhui** [comment]
@chengh2016 此处交流不便，QQ私聊。

**Comment by chengh2016** [comment]
谢谢，已解决，是我对接的播放器在reset()之前需要清除之前的数据
