### ISSUE TITLE
怎么在视频播放的时候设置header?

### ISSUE THREAD

**Issue by tmxd09887** [jiajunhui/PlayerBase#59]
有的视频，需要添加referer才能正常播放，就是访问视频的时候要设置header

谢谢

**Comment by jiajunhui** [comment]
```java
DataSource data = new DataSource("http://url...");
HashMap<String, String> headers = new HashMap();
//...
data.setExtra(headers);
```

**Comment by tmxd09887** [comment]
headers.put("referer", "https://xxx");

 dataSource.setExtra(headers);

添加了referer，无效啊

返回错误跟没添加一样
ExoMediaPlayer: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403

**Comment by jiajunhui** [comment]
晚上我看一下

**Comment by tmxd09887** [comment]
多谢大佬

**Comment by jiajunhui** [comment]
@tmxd09887 应该可以了，使用最新依赖试一下
```gradle
implementation 'cn.jiajunhui:exoplayer:3332_291_006'
```

**Comment by tmxd09887** [comment]
试过了，成功了。

谢谢大佬。
