### ISSUE TITLE
请问现在支持多少种视频格式，以及支持外挂字幕吗？

### ISSUE THREAD

**Issue by waitinghc** [jiajunhui/PlayerBase#6]

**Comment by jiajunhui** [comment]
格式的支持取决于你接入的解码器，框架内部接入了MediaPlayer，其它的解码器需要自己接入。demo示例接入了ijkplayer和exoplayer，目前demo中自带的ijkplayer是较多格式版本的解码库，ijkplayer没有外挂字幕的相关API，可以尝试在Java层自己实现字幕解析呈现。
