### ISSUE TITLE
请问如何获取MediaPlayer？

### ISSUE THREAD

**Issue by choimroc** [jiajunhui/PlayerBase#61]
您好，因为项目需求，我需要获取MediaPlayer来进行一些操作，请问有没有暴露的方法可以直接获取呢？我看了好一会儿源码都没有找到。谢谢

**Comment by jiajunhui** [comment]
@choimroc 你需要什么操作？框架没有提供暴露实际解码器对象的方法，主要是考虑到暴露就会出现交叉耦合。框架提供的有和内部解码器通信的方式，你可以试试，有个option方法。具体不明白，可以群里交流，这里沟通不便。

**Comment by choimroc** [comment]
@jiajunhui 已经找到了暴露的方法，需要getAudioSessionId，感谢
