### ISSUE TITLE
Demo列表中内存泄漏的问题

### ISSUE THREAD

**Issue by Redoteam** [jiajunhui/PlayerBase#64]
Android 系统4.4.4
手机型号：oppo
复现步骤：进入列表视频——>点击视频标题，进入视频详情页面——>返回
重复上面的步骤，金丝雀框架就会报出内存泄漏

[2019-01-08_13-30-07_980.hprof.zip](https://github.com/jiajunhui/PlayerBase/files/2735300/2019-01-08_13-30-07_980.hprof.zip)
![screenshot_2019-01-08-13-39-10-503](https://user-images.githubusercontent.com/17085002/50811886-69cc9180-134b-11e9-927e-2f70819f2ab7.png)
![screenshot_2019-01-08-13-38-08-632](https://user-images.githubusercontent.com/17085002/50811887-69cc9180-134b-11e9-8ee4-6d664e4238e7.png)

**Comment by jiajunhui** [comment]
这个我这边暂未复现，我抽空看一下。

**Comment by Redoteam** [comment]
我今天也试了下，复现的概率不高，后来就乱点了，出现了3次，可能是昨天漏了哪一步

**Comment by Redoteam** [comment]
好的

**Comment by Redoteam** [comment]
点击标题的时候，速度快点，频率快点，进去详情之后，又赶紧退出来，然后依次重复这个步骤，有几率出现这个问题
