### ISSUE TITLE
建议TimerCounterProxy 的时间间隔可自定义

### ISSUE THREAD

**Issue by zhuxiaole** [jiajunhui/PlayerBase#66]
时间间隔为1秒会有一些bug，建议这个时间间隔可以自定义

**Comment by jiajunhui** [comment]
什么bug?

**Comment by zhuxiaole** [comment]
> 什么bug?

比如视频总长度10秒，显示播到9秒就complete了。建议把间隔改为400或者500毫秒。或者可自定义。

**Comment by jiajunhui** [comment]
这个问题我下个版本会在库中统一做个处理，修改间隔时间并不合适，只能说改小了能降低这种现象的概率。

**Comment by jiajunhui** [comment]
@zhuxiaole 用最新版本，已发版。
