### ISSUE TITLE
视频播放完成后记录的时间点问题

### ISSUE THREAD

**Issue by zhuxiaole** [jiajunhui/PlayerBase#67]
视频complete状态后，RecordProxyPlayer将记录的时间点置为0，如果调用stop、reset、destroy等方法，RecordProxyPlayer又会重新记录时间点。

**Comment by jiajunhui** [comment]
@zhuxiaole 多谢指正。已修复，明日发版。

**Comment by jiajunhui** [comment]
@zhuxiaole 版本已发，可查验。
