### ISSUE TITLE
手势与RecyclerView的touch事件冲突

### ISSUE THREAD

**Issue by zhuxiaole** [jiajunhui/PlayerBase#68]
BaseGestureCallbackHandler中的onScroll、onSingleTapUp、onDoubleTap这些方法的返回值，是否应该在Cover处理了touch事件时返回true呢？

**Comment by jiajunhui** [comment]
框架内部是做了个默认的手势事件分发，这个在SuperContainer中可以设置为关闭然后自行处理。在RecyclerView的使用中场景很多，如果不满足需求建议关闭掉框架的内部处理而自行处理。目前框架内部对这块的处理确实是有些不太合适的地方，后期发版会优化这块儿。

**Comment by ooyellow58** [comment]
How to close the gesture control internally?
