### ISSUE TITLE
点播，长视频，首帧出来很慢

### ISSUE THREAD

**Issue by aheadlcx** [jiajunhui/PlayerBase#7]
长视频，比如 2G  120分钟的视频，要卡很久。

**Comment by jiajunhui** [comment]
有几点需要明确一下：
1. 框架属于播放基础架构不处理解码部分，框架自带的是MediaPlayer的解码。
2. 其他的解码器需要自己接入并调优配置。
还有，我找了个2G大约120分钟的RMVB视频放到服务器上测试了下，使用ijk播放，平均起播时间基本维持在2秒，并未出现你说的卡很久。不太清楚你的视频源信息，起播时间与视频流有一定关系（DASH或HLS）以及视频的分发网络有关。

**Comment by aheadlcx** [comment]
我测试的 MP4  3G  120分钟，首帧出来需要14秒。谢谢你的回答。
