### ISSUE TITLE
app例子里setTotalTime方法，不显示小时单位

### ISSUE THREAD

**Issue by tmxd09887** [jiajunhui/PlayerBase#73]
文件位置在cover/ControllerCover.java    

private void setTotalTime(int duration){
        mTotalTime.setText(TimeUtil.getTime(mTimeFormat, duration));//默认不显示小时单位
        mTotalTime.setText(TimeUtil.getTimeSmartFormat(duration));//改成这个可以显示小时单位
    }

这算BUG吗？

谢谢

**Comment by jiajunhui** [comment]
我目前手头没有超过1小时的视频可以测试，这个你debug看下在onTimerUpdate方法内mTimeFormat被初始化时的格式是否是合适的格式，先确认下问题在哪。

**Comment by tmxd09887** [comment]
onTimerUpdate方法里的mTimeFormat是错的，返回的是%02d:%02d（TIME_FORMAT_01 ）

但是这个文件playerbase/utils/TimeUtil.java里，代码看没错啊

**Comment by tmxd09887** [comment]
更新了新版本的avplayer/cover/ControllerCover.java文件就好了，引入duration的值不对
