### ISSUE TITLE
seek播放视频回退

### ISSUE THREAD

**Issue by wangjianjun0815** [jiajunhui/PlayerBase#79]
播放本地视频seek到一个位置播放,进度条回退几秒钟

**Comment by jiajunhui** [comment]
这个取决于视频源，与关键帧定位有关。视频在跳转到相应的 position 位置缺少关键帧的情况下，调用 seekTo 方法是无法在当前位置开始播放。这时会寻找离指定 position 最近的关键帧位置开始播放。
