### ISSUE TITLE
DataProvider冗余

### ISSUE THREAD

**Issue by imaiya** [jiajunhui/PlayerBase#8]
这个应该不属于框架处理范围

**Comment by jiajunhui** [comment]
开发过程中确实是有这方面的需要，只是对数据生产的包装，并没有多余的功能。这个非必须，完全可以自己处理数据的填充。

**Comment by imaiya** [comment]
@jiajunhui 谢谢回复,DataProvider确实有一定需要;另外在demo中我发现了两个很小的问题,1.使用ijkpalyer播放时拖动进度条,loading展示一下后立马消失,加载过程中loading没有正常展示(应该是ijkplayer本身的监听器存在小问题);2.使用ExoPlayer播放完成后,点击下一个,下一个视频开始播放后CompleteCover组件还处于展示状态(调试后发现是这个过程中PLAYER_EVENT_ON_PLAY_COMPLETE事件会被回调导致).以上两个小问题均是在demo的BaseVideoView中发现的

**Comment by jiajunhui** [comment]
@imaiya 感谢提供问题线索。demo中exoplayer的bug已修复，如有兴趣安装最新demo验证即可。
