### ISSUE TITLE
循环播放的问题

### ISSUE THREAD

**Issue by netdolphin** [jiajunhui/PlayerBase#80]
我需要循环播放，用了rePlay(0)无效。控制台反复出现
04-08 12:34:27.252 28477-28477/BaseActivity: onPlayerEvent: PAUSE
04-08 12:34:27.319 28477-28477/BaseActivity: onPlayerEvent: RESUME
04-08 12:34:27.381 28477-28477/BaseActivity: onPlayerEvent: PAUSE
04-08 12:34:27.319 28477-28477/BaseActivity: onPlayerEvent: RESUME

**Comment by jiajunhui** [comment]
使用Loop设置即可
