### ISSUE TITLE
支持多个实例吗，会不会有很多单例的东西

### ISSUE THREAD

**Issue by najiutan** [jiajunhui/PlayerBase#82]
支持多个实例吗，会不会有很多单例的东西

**Comment by jiajunhui** [comment]
PlayerBase内部没有单例的限制。能不能多个实例主要看解码器了，我测试过多实例，可以播，但是比较吃性能。

**Comment by najiutan** [comment]
> PlayerBase内部没有单例的限制。能不能多个实例主要看解码器了，我测试过多实例，可以播，但是比较吃性能。

好的，谢谢解答，回复神速啊，赞一个
