### ISSUE TITLE
cpu占用率是原始ijkplayer的两倍

### ISSUE THREAD

**Issue by najiutan** [jiajunhui/PlayerBase#84]
cpu占用率是原始ijkplayer的两倍

**Comment by jiajunhui** [comment]
实测了一下PlayerBase和IJKPlayerdemo，在尽量保持所有配置以及环境相同的情况下播放同一视频，二者CPU占有率波动范围均大致维持在4%-12%之间，具体你说的两倍不知道是如何测试的。
以下为二者测试时的资源和配置
测试设备：华为P9
视频源：https://mov.bn.netease.com/open-movie/nos/mp4/2017/05/31/SCKR8V6E9_hd.mp4
解码器：均使用PlayerBase的demo中的so包
配置：均开启mediacodec，render都使用SurfaceView（PlayerBase默认TextureView，ijkdemo默认SurfaceView，TextureView的CPU占用会较高一点），开启OpenGL

**Comment by najiutan** [comment]
> 实测了一下PlayerBase和IJKPlayerdemo，在尽量保持所有配置以及环境相同的情况下播放同一视频，二者CPU占有率波动范围均大致维持在4%-12%之间，具体你说的两倍不知道是如何测试的。
> 以下为二者测试时的资源和配置
> 测试设备：华为P9
> 视频源：https://mov.bn.netease.com/open-movie/nos/mp4/2017/05/31/SCKR8V6E9_hd.mp4
> 解码器：均使用PlayerBase的demo中的so包
> 配置：均开启mediacodec，render都使用SurfaceView（PlayerBase默认TextureView，ijkdemo默认SurfaceView，TextureView的CPU占用会较高一点），开启OpenGL

同样一个视频：https://mov.bn.netease.com/open-movie/nos/mp4/2016/01/11/SBC46Q9DV_hd.mp4，用楼主的这个cpu 26%，用ijkplayer 10%

**Comment by najiutan** [comment]
> 实测了一下PlayerBase和IJKPlayerdemo，在尽量保持所有配置以及环境相同的情况下播放同一视频，二者CPU占有率波动范围均大致维持在4%-12%之间，具体你说的两倍不知道是如何测试的。
> 以下为二者测试时的资源和配置
> 测试设备：华为P9
> 视频源：https://mov.bn.netease.com/open-movie/nos/mp4/2017/05/31/SCKR8V6E9_hd.mp4
> 解码器：均使用PlayerBase的demo中的so包
> 配置：均开启mediacodec，render都使用SurfaceView（PlayerBase默认TextureView，ijkdemo默认SurfaceView，TextureView的CPU占用会较高一点），开启OpenGL

![image](https://user-images.githubusercontent.com/15669579/56093992-7b50a700-5f01-11e9-91c3-06beaaa14a08.png)
![image](https://user-images.githubusercontent.com/15669579/56094003-8f94a400-5f01-11e9-82c0-565bf015fc4e.png)
如图，我是用楼主的BaseVideoView测试的，除了改了地址，什么都没改动，没点击任何按钮，手机三星I9500

**Comment by jiajunhui** [comment]
请尽量保持二者测试的环境和配置一样，如果还有问题再讨论是否是库的问题。

**Comment by najiutan** [comment]
> 请尽量保持二者测试的环境和配置一样，如果还有问题再讨论是否是库的问题。

同一个手机，我也关闭了record

**Comment by najiutan** [comment]
> 请尽量保持二者测试的环境和配置一样，如果还有问题再讨论是否是库的问题。

同一个网络环境
