### ISSUE TITLE
开启混淆后无法播放，混淆问题

### ISSUE THREAD

**Issue by diswy** [jiajunhui/PlayerBase#85]
根据文档配置了混淆，不开混淆，视频可正常播放，当开启了混淆后，视频播放页无法播放，已经让对应的activity都keep了，请问还需要怎么配置？有什么解决办法么

**Comment by jiajunhui** [comment]
测试了一下混淆，没问题的。如果播放不了，请注意一下有没有什么其他的报错或者日志输出。

**Comment by diswy** [comment]
您好，就是没有报错，只是出现了无法播放，当我没开混淆的时候，会Loding，然后播放，当我开启混淆后，就不会执行LODING 也没有播放。请问此类问题如何排查一下？

**Comment by jiajunhui** [comment]
应该是你的混淆配置有问题。比如一些基本的混淆配置：保护native方法、保护注解等等……

**Comment by diswy** [comment]
非常感谢作者回答，我自己在多测试测试找找原因
