### ISSUE TITLE
多个视频无缝拼接播放问题

### ISSUE THREAD

**Issue by zhuhonglei** [jiajunhui/PlayerBase#86]
使用ijk解码,配置如下:
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);
依然报错:
Unsafe file name

**Comment by may7be** [comment]
同问
