### ISSUE TITLE
在 viewpage无法全屏

### ISSUE THREAD

**Issue by zhangchengzccz** [jiajunhui/PlayerBase#91]
有单独viewpage全屏的demo么？我看了你的列子  而且把列表的改成viewpage发现不行，会有问题

**Comment by jiajunhui** [comment]
参见demo中ViewPagerPlayActivity

**Comment by zhangchengzccz** [comment]
> 参见demo中ViewPagerPlayActivity

ViewPagerPlayActivity  我说的是 viewPager从小屏切换到全屏的，参见demo中ViewPagerPlayActivity  这个里面直接是匹配父窗体，取决的是父窗体的大小的，  我想要的是listView那种，小屏播放然后能单独切成大屏，只不过是要在ViewPager实现， 我改了下代码还是没有实现

**Comment by jiajunhui** [comment]
参考ListPlay
