### ISSUE TITLE
播放手机录制的视频旋转90度

### ISSUE THREAD

**Issue by 0xRookie** [jiajunhui/PlayerBase#98]
手机录制竖屏的视频播放的时候是横着的。。。怎么让它播放也是竖着。。

**Comment by 0xRookie** [comment]
在Activity中注册OnPlayerEventListener：（并没由用）
case OnPlayerEventListener.PLAYER_EVENT_ON_VIDEO_ROTATION_CHANGED:
                if(bundle!=null){
                    //if rotation change need update render.
                   int mVideoRotation = bundle.getInt(EventKey.INT_DATA);
                    LogHelper.d("onVideoRotationChange : videoRotation = " + mVideoRotation);
                    if(mVideoView.getRender()!=null) {
                        mVideoView.getRender().setVideoRotation(mVideoRotation);
                    }
                }
                break;

**Comment by 0xRookie** [comment]
原来用的ijk，换成EXO就好了。
ijk播放的时候还卡顿，2秒的视频能放7秒。
手机：huawei mate9。视频是使用系统相机录像录制的。

**Comment by jiajunhui** [comment]
或许是ijk的处理有问题，能提供下视频源吗？
